### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Czh3** [dschuhmacher/transport#1]
Hi the team, 

It reported an error when I install the package by install.packages("transport").

installing to /netscr/miniconda3/lib/R/library/00LOCK-transport/00new/transport/libs
** R
Error in parse(outFile) :
  /tmp/RtmpTM8Lyz/R.INSTALLe03766aa17fa9/transport/R/unbalanced_wpp.R:18:30: unexpected input
17:     coords <- rbind(a$coordinates, b$coordinates)
18:     span <- apply(coords, 2, \
                                 ^
ERROR: unable to collate and parse R files for package ‘transport’
* removing ‘/netscr/miniconda3/lib/R/library/transport’

The downloaded source packages are in
	‘/tmp/Rtmpr0BTy0/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("transport") :
  installation of package ‘transport’ had non-zero exit status

Do you know what happens, and how can I address this error. 

Thanks,
Chao

**Comment by dschuhmacher** [comment]
It seems your R version does not know the shorthand syntax for anonymous functions (which means it must be about three or more years old). The quickest solution is to update to the latest R version (or at least version 4.1.0).

**Comment by Czh3** [comment]
Thanks for the quick response. I tried conda installation(conda install conda-forge::r-transport), which works for me. So it seems not because of the R version.

sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS/LAPACK: /netscr/miniconda3/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] transport_0.12-4                          org.Hs.eg.db_3.13.0                       pwr_1.3-0                                
 [4] rstatix_0.7.0                             pals_1.7                                  harmony_1.0

**Comment by dschuhmacher** [comment]
I still think it was because of the R version: the reason why it works now appears to be that you have now an old R version *and* an old version of the transport package (0.12-4 rather than 0.15-0). If that works out for you, it's fine of course.

**Comment by Czh3** [comment]
Thanks. I think you are right. Do you think I should upgrade to transport v0.15. Do these two versions have big difference?

**Comment by dschuhmacher** [comment]
For optimal transport on images or unstructured objects (where you specify the cost matrix yourself), there should be hardly any difference. Since v0.12-4 we had some bug fixes for semidiscrete transport and quite a bit of added functionality for weighted point patterns and unbalanced OT. For details, see the NEWS file.

**Comment by Czh3** [comment]
Thank you very much!
