### ISSUE TITLE
transport::unbalanced gives wrong result when no transport is necessary and `output = "dist"` and `p = 1`

### ISSUE THREAD

**Issue by Noskario** [dschuhmacher/transport#2]
Have a look at the following code:
```
library(transport)
unbalanced(
  c(0,0,3) |> as.matrix() |> pgrid(),
  c(0,0,2) |> as.matrix() |> pgrid(),
  C = 1,
  output = "dist"
)
unbalanced(
  c(0,0,3) |> as.matrix() |> pgrid(),
  c(0,0,2) |> as.matrix() |> pgrid(),
  C = 1,
  output = "all"
)$dist

```
It gives 0 and 1. Only the second result is correct.

With `p = 2` this does not happen (both results correctly 1).

**Comment by Noskario** [comment]
Unrelated to this problem, but I am curious: Is there some kind of unbalanced1D like there is wasserstein1D?

**Comment by dschuhmacher** [comment]
I cannot reproduce this on my system. With transport 0.15-4, I get 1 in both cases. If it persists, could you give me your `sessionInfo()`?

**Comment by dschuhmacher** [comment]
> Unrelated to this problem, but I am curious: Is there some kind of unbalanced1D like there is wasserstein1D?

There is currently no unbalanced1d. The package has grown over many years, quite wildly and mostly based on my own needs and interests. The only reason why there is wasserstein1d is popular request (it was added quite late in the history of the package). Feel free to open a PR or feature request if this is interesting for you.

**Comment by Noskario** [comment]
I am sorry, I had version transport_0.14-6, now I have transport_0.15-4 and it works!
